import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { usePathname } from 'next/navigation';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params, searchParams }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
